server:
  port: 8080
  servlet:
    context-path: /
spring:
  kafka:
    bootstrap-servers: 192.168.99.100:9092
    client-id: dealer
  cloud:
    stream:
      kafka:
        streams:
          binder:
            application-id: dealer
      bindings:
        request:
          destination: request
          contentType: application/json
        response:
          destination: response
          contentType: application/json
